# Generated by Django 5.2.12 on 2026-03-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_refeicao_opcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes'),
        ),
    ]
